library(shiny, warn.conflicts = FALSE)
library(shinyjs, warn.conflicts = FALSE)
#library(dplyr)
library(magrittr, warn.conflicts = FALSE)
library(purrr, warn.conflicts = FALSE)
#library(Hmisc)
library(RJSONIO)
library(stringr)
library(writexl)
library(zip, warn.conflicts = FALSE)
library(shinyBS)

source('functions/eFormsParseJSON_basic.r')
source('functions/eFormsParseJSONtext.r') 
source('functions/eFormsOrganizeData_byTable.r')
source('functions/karenParseEVJ.R')

metadata <- readRDS("data/metadata.rds")