install.packages("shiny",dependencies=TRUE,type='binary')
install.packages("shinyjs",dependencies=TRUE,type='binary')
#install.packages('dplyr',dependencies=TRUE,type='binary')
install.packages('purrr',dependencies=TRUE,type='binary')
#install.packages("Hmisc",dependencies=TRUE)
install.packages("RJSONIO",dependencies=TRUE,type='binary')
install.packages("stringr",dependencies=TRUE,type='binary')
install.packages("writexl",dependencies=TRUE,type='binary')
install.packages("zip",dependencies=TRUE,type='binary')
install.packages("shinyBS",dependencies=TRUE,type='binary')
install.packages("kableExtra",dependencies=TRUE,type='binary')
install.packages("knitr",dependencies=TRUE,type='binary')
#install.packages("magick",dependencies=TRUE,type='binary')

