install.packages("shiny",dependencies=TRUE,type='binary')
install.packages("shinyjs",dependencies=TRUE,type='binary')
install.packages("reshape2",dependencies=TRUE,type='binary')
install.packages("plyr",dependencies=TRUE,type='binary')
# install.packages("tidyverse",dependencies=TRUE)
install.packages('tibble',dependencies=TRUE,type='binary')
install.packages('dplyr',dependencies=TRUE,type='binary')
install.packages('purrr',dependencies=TRUE,type='binary')
# install.packages("Hmisc",dependencies=TRUE)
install.packages("RJSONIO",dependencies=TRUE,type='binary')
install.packages("stringr",dependencies=TRUE,type='binary')
install.packages("writexl",dependencies=TRUE,type='binary')
install.packages("zip",dependencies=TRUE,type='binary')
install.packages("shinyBS",dependencies=TRUE,type='binary')
# install.packages("cairo",dependencies=TRUE)
install.packages("kableExtra",dependencies=TRUE,type='binary')
install.packages("knitr",dependencies=TRUE,type='binary')
#install.packages("magick",dependencies=TRUE,type='binary')

