install.packages("shiny",dependencies=TRUE)
install.packages("shinyjs",dependencies=TRUE)
install.packages("reshape2",dependencies=TRUE)
install.packages("plyr",dependencies=TRUE)
#install.packages("tidyverse",dependencies=TRUE)
install.packages('tibble',dependencies=TRUE)
install.packages('dplyr',dependencies=TRUE)
install.packages('purrr',dependencies=TRUE)
install.packages("Hmisc",dependencies=TRUE)
install.packages("RJSONIO",dependencies=TRUE)
install.packages("stringr",dependencies=TRUE)
install.packages("writeexl",dependencies=TRUE)
install.packages("zip",dependencies=TRUE)
install.packages("shinyBS",dependencies=TRUE)
# install.packages("cairo",dependencies=TRUE)
install.packages("kableExtra",dependencies=TRUE)
install.packages("knitr",dependencies=TRUE)

